<?php $this->load->view('includes/front/leftsidebar');?>


<div class="container inner">
<div class="row">    		
	    		<div class="col-sm-12">    			   			
					<h2 class="title text-center">Privacy Policy</h2>
				</div>			 		
			</div> 

<p>Sarvmatic Technology ( We”, “Our”, “Zoogol” or “Us”, where such expression shall unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns) own and/ or operate the website and mobile application Zoogol.com (“Website”, “Our Website”, “Site”).</p><br>
<p>For the purpose of providing the Services (as defined in clause 1 below), Zoogol is required to collect and use certain information of the users of the Website (“Users”) using the Services and involves capturing, storage and transmission of such information. This privacy policy ("Privacy Policy"/ “Policy”) explains how We collect, use, share and protect personal information of the Users of the Services (jointly and severally referred to as “You”, “Your”, “Yourself” or “User” or “Users” in this Privacy Policy). We have created this Privacy Policy to ensure our steady commitment to the privacy of the information of the Users who interact with our Services. Your use of and access to the Services is subject to this Privacy Policy and our Terms and Conditions. Any capitalized term used, but not defined, in this Privacy Policy shall have the meaning attributed to it in our Terms and Conditions.</p><br>
<p>The headings used herein are only for the purpose of arranging the various provisions of the Privacy Policy. The headings are for the purpose of reference only and shall not be interpreted to limit or expand the provisions of the clauses contained therein.</p>
<h4><b>1. Definitions</b></h4>
<p>We collect information about you when you sign/fill up Zoogolmembership registration form, order or activate a Zoogol on our website, provide us with feedback, enter a promotion or competition, and/or contact us with your account. This information may include details such as your name, email address, telephone number and any other information you provide, such as age group, interests and preferences and you are not anonymous to us</p>
<p>        "Personal Information” shall have the same meaning as given in Rule 2(1)(i) of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 to mean any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available to a body corporate, is capable of identifying such person.</p>
<h4><b>2. WHY THIS PRIVACY POLICY?</b></h4>

<p>This Privacy Policy is published in compliance with, inter alia,</p>
<ol> <li>Section 43A of the Information Technology Act, 2000;</li>
<li>Regulation 4 of the SPI Rules; and</li>
<li>Regulation 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 (“Intermediaries Guidelines”)</li>
<li>The type of information collected from the Users, including Sensitive Personal Data or Information;</li>
<li>The purpose, means and modes of usage of such information; and</li>
<li>How and to whom we will disclose such information</li>
</ol>      

<h4><b>3. GENERAL</b></h4>

    <p><b>a.</b>The User unequivocally agrees that this Policy and the aforementioned Terms and Conditions constitute a legally binding agreement between the User and Zoogol, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by Zoogol including the Services, and that the same shall be deemed to be incorporated into the Terms and Conditions, and shall be treated as part of the same.</p></br>
      <p><b>b.</b>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. Further, this document is published in accordance with the provisions of the SPI Rules and Intermediaries Guidelines.</p>
      <p><b>c.</b>The terms ‘Party’ and ‘Parties’ shall respectively be used to refer to the User and Zoogol individually and collectively, as the context so requires.</p>
     <p><b>d.</b>The headings of each section in this Policy are only for the purpose of organizing the various provisions under this Policy in an orderly manner and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.</p>
    <p><b>e.</b>The Parties expressly agree that subject to clause 13 of this Policy, Zoogol retains the sole and exclusive right to amend or modify the Policy and the aforementioned Terms and Conditions without any prior permission or intimation to the User keeping in mind best practices and laws set by State/Central Government of India, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the Policy and Terms and Conditions and stay updated on their provisions and requirements. If the User continues to use the Services following such a change, the User will be deemed to have consented to any and all amendments/ modifications made to the Policy and Terms and Conditions. In so far as the User complies with the Policy and Terms and Conditions, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter, access and use the Services.</p>
    

<h4><b>4. COLLECTION AND HANDLING OF PERSONAL INFORMATION</b></h4>

<p>Privacy of the Parties is of prime importance to Us and all Services are strictly designed within the jurisdiction of laws defined by the Government of India.</p>

<p>Generally, the Services require us to know who you are so that we can best meet your needs. When you access the Services, we may ask you to voluntarily provide us with certain information that personally identifies you or could be used to personally identify you. Without prejudice to the generality of the above, information collected by us from you may include (but is not limited to) the following:</p>
<p><b>a.</b> Contact data (such as your email address and phone number);</p>
    <p><b>b.</b> User name and passwords;</p>
    <p><b>c.</b> Demographic data (such as your name, gender, age, your date of birth and your pin code);</p>
    <p><b>d.</b> Data regarding your usage of the services and other transactions made by or with you through the use of Services;</p>
	<p><b>e.</b> Information about your clicks on and from Zoogol mobile device, web browser, web and mobile browsing patterns, retailer preferences</p>
	<p><b>f.</b> Your bank account information including name of the bank account, account number, IFSC code, bank branch or any other payment related information</p>
	<p><b>g.</b> Any other information that you voluntarily choose to provide to us (such as information shared by you with us through emails, calls or letters, your work details, home / work address, your family details, details about transactions done on ecommerce sites, screenshots of transactions, order IDs for transactions, alternate numbers and emails and various other information provided from time to time).</p>
	<p> The information collected from You by Us shall constitute ‘Personal Information’ or ‘Sensitive Personal Data Information’ under the SPI Rules.</p>
	
	
<h4><b>5. PRIVACY STATEMENTS</b></h4>

<p>The User expressly agrees and acknowledges:</p>
<p><b>a.</b> Information that is freely available in the public domain or accessible under the Right to Information Act, 2005 or any other law will not be considered as ‘Personal Information’ or ‘Sensitive Personal Data or Information’ for the purposes of this Policy. <br>That Zoogol may automatically track information about the User based on the User’s IP address and the User’s behaviour on the Platform, and the User expressly consents to the same. The User is aware that this information may be used to conduct internal research on user demographics, interests, and behaviour, to enable Zoogol to better understand, and cater to the interests of the Users. Further, the User is expressly made aware that such information may include the User’s computer & web browser information, the User’s IP address, mobile device details etc. The linkage between User’s IP address and User’s personally identifiable information may be shared with or disclosed to third parties in order to facilitate the provisions of the Services to You. The User hereby consents to the sharing of such information to such third parties as may be determined by Zoogol from time to time. Further, we may also share and/or disclose some of the aggregate findings (not the specific data) in anonymized form (i.e., non-personally identifiable) with third parties for market research and new feature development.</p>
    <p><b>b.</b> That any and all information pertaining to the User collected by Zoogol, whether or not directly provided by the User to Zoogol, including but not limited to personal correspondence such as emails or letters or SMS or WhatsApp or calls, feedback from other users or third parties regarding the User’s activities or postings on the Platform, etc., may be collected and compiled by Zoogol into a file/folder specifically created for/allotted to the User, and the User hereby expressly consents to the same. 
	<br>Also, in order to keep You informed of Your activities on the Website we occasionally send You emails, SMS, App notifications and other marketing communication. These include Your transaction messages to show how much You have earned, referral messages that show You how much You have earned from referrals, payment confirmations for payments to You and, important administrative messages and messages to confirm Your activities on the Website. These emails are not shared with anyone else apart from You.
<br>
We also send newsletters, SMSs, App notifications, browser notification and other marketing that features some of our best ideas to help You save more. You may choose not to receive this marketing communication from Zoogol by informing Us at any time.
<br>
We do not support spamming by our members and we explicitly prohibit it in our Terms and Conditions. If You would like to report an incident of spamming, please contact us so we can investigate and take suitable action.</p>
    <p><b>c.</b> That the contact information provided to Zoogol may be used to send the User offers and promotions, whether or not based on the User’s previous interests, and the User hereby expressly consents to receiving the same. The User may choose to unsubscribe from promotional communications by clicking on the ‘unsubscribe’ link provided at the end of such promotional communication or by emailing us on contact@Zoogol.com</p>
    <p><b>d.</b> That Zoogol may occasionally request the User to complete optional online surveys. These surveys may require the User to provide contact information and demographic information (like zip code, age, income bracket, sex, etc.). The User is aware that this information is used to improve/customise the Services for the benefit of the User and providing all users of the Platform with services that Zoogol believes they might be interested in availing of.</p>
	<p><b>e.</b> That Zoogol may keep records of electronic communications and telephone calls received and made for support or other purposes for the purpose of administration of Services, customer support, research and development and for better assistance to Users.
That Zoogol may occasionally request the User to write reviews for services availed of by the User from the Platform. The User is aware that such reviews will help potential users of the Platform in availing the Services, and the User hereby expressly authorizes Zoogol to publish any and all reviews written by the User on the Platform, along with the User’s name and certain contact details, for the benefit and use of other users.</p>
	<p><b>f.</b> Nothing contained herein shall be deemed to compel Zoogol to store, upload, publish, or display in any manner content/reviews/surveys/feedback submitted by the User, and the User hereby expressly authorizes Zoogol to remove from the Platform any such content, review, survey, or feedback submitted by the User, without cause or being required to notify the User of the same.</p>
	<p><b>g.</b> Generation and collection of ‘Sensitive Personal Data or Information’ in accordance with Information Technology Act, 2000 as amended from time to time and allied rules requires the User’s express consent. By affirming assent to this Policy as well as clicking on the “I agree with Terms and Policy” button at the time of registration, the User provides consent to such generation and collection as required under applicable laws.</p>
	<p><b>h.</b> The User is responsible for ensuring that the accuracy of the information submitted to Zoogol. The User may correct, delete inaccuracies, or amend information by contacting Zoogol through email on contact@Zoogol.com. Zoogol will make good faith efforts to make requested changes in the databases as soon as reasonably practicable. If the User provides any information that is untrue, inaccurate, out of date or incomplete (or becomes untrue, inaccurate, out of date or incomplete), or Zoogol has reasonable grounds to suspect that the information provided by the User is untrue, inaccurate, out of date or incomplete, Zoogol may, at its sole discretion, discontinue the provision of the Services to you as per the provisions laid down in the Terms and Conditions. There may be circumstances where Pouring Pounds will not correct, delete or update your Personal Data, including (a) where the Personal Data is opinion data that is kept solely for evaluative purpose; and (b) the Personal Data is in documents related to a prosecution if all proceedings relating to the prosecution have not been completed.</p>
	<p><b>i.</b> All the information provided to Us by a User, including Sensitive Personal Data or Information, is voluntary. User has the right to withdraw his/ her/ its consent at any time, in accordance with the terms of this Privacy Policy, and the Terms and Conditions applicable to such User, it being however clarified that withdrawal of consent will not be retroactive. If the User wishes to delete his/her account or request that Zoogol no longer uses the User’s information to provide Services, the User may contact Zoogol on contact@Zoogol.com. We shall not retain such information for longer than is required for the purposes for which the information may lawfully be used or is otherwise required under any other law for the time being in force. After a period of time, your data may be anonymized and aggregated, and then may be held by us as long as necessary for us to provide our Services effectively, but our use of the anonymized data will be solely for analytic purposes. Please note that your withdrawal of consent, or cancellation of account may result in Pouring Pounds being unable to provide you with its Services or to terminate any existing relationship Pouring Pounds may have with you.</p>
	
	<p><b>j.</b> If you wish to opt-out of receiving non-essential communications such as promotional and marketing-related information regarding the Services, please send us an email at contact@Zoogol.com.</p>
	
	
	
<h4><b>6. OUR USE OF YOUR INFORMATION</b></h4>

<p>All the information provided to Zoogol by a User, including Personal Information or any Sensitive Personal Data or Information, is voluntary. Such information in its original form may be shared with any Third Parties in furtherance of the consent from the User as provided hereunder. You understand that Zoogol may use certain information of yours, which has been designated as Personal Information or ‘Sensitive Personal Data or Information’ under the SPI Rules for the following purposes:</p>
<p><b>a.</b> providing you the Services;</p>
    <p><b>b.</b> taking product & Services feedback;</p>
    <p><b>c.</b> for offering new products or services and marketing of the Services;</p>
    <p><b>d.</b> for analysing software usage patterns for improving product design and utility;</p>
	<p><b>e.</b> for providing the services of generating alerts/reminders/SMS for offers and also for internal record.</p>
	<p><b>f.</b> for commercial purposes and in an aggregated or non-personally identifiable form for research, statistical analysis and business intelligence purposes</p>
	<p><b>g.</b> for sale or transfer of such research, statistical or intelligence data in a non-personally identifiable form to third parties and affiliates;</p>
	<p><b>g.</b> debugging customer support related issues; and</p>
	<p> We may use your tracking information such as IP addresses, and or Device ID to help identify You and to gather broad demographic information.</p>
	<p> In case we are acquired by or merged with another company, We shall transfer information disclosed by You and information about You to the company we are acquired by or merged with, and such company will have the right to continue to use the User’s Personal Information and/ or other information that a User provides to Us. In the event of a merger or acquisition, We shall notify You by email/by putting a notice on the Website and/ or Application before Your Personal Information is transferred and becomes subject to a different privacy policy.

The Users expressly agree and acknowledge that Zoogol collects and stores the User’s Personal Information and/or Sensitive Personal Information in a secure cloud based platform which is provided by the User from time to time on the Platform or while using other Services.

The User is aware that this information will be used by Zoogol to deliver its services and help customize/improve the Platform experience safer and easier but no personally identifiable information will be shared with any Third Party under any circumstances without User’s explicit consent unless directed by the law.</p>
	<p> Zoogol may need to disclose/ transfer User’s Personal Information to the following third parties for the purposes mentioned in this Privacy Policy, and the Terms and Conditions as applicable to such User:</p>
<p><b>a.</b> To government institutions/ authorities to the extent required:</p>
    <ol>
	<li>under the laws, rules, and regulations and/ or under orders of any relevant judicial or quasi-judicial authority;</li>
	<li>to protect and defend the rights or property of Zoogol;</li>
	<li>to fight fraud and credit risk;</li>
	<li>to enforce Zoogol’s Terms and Conditions applicable to the Users; or</li>
	<li>when Zoogol, in its sole discretion, deems it necessary in order to protect its rights or the rights of others.</li>
	</ol>

 <h4><b>7. YOUR RIGHTS</b></h4> 
<p><b>1.</b> Access to Personal Data. You have the right to access, review and request a physical or electronic copy of information held about you. You also have the right to request information on the source of your Personal Information/Sensitive Personal Information.</p> 
<p><b>2.</b> Additional rights (e.g. modification, deletion of Personal Data).Where provided by law, you can (i) request deletion, the portability, correction or revision of your User Information; (ii) limit the use and disclosure of your Personal Data; and (iii) revoke consent to any of our data processing activities. Provided that, we may be required to retain some of your User Information after you have requested deletion, to satisfy our legal or contractual obligations. We may also be permitted by applicable laws to retain some of your User Information to satisfy our business needs.</p>


<h4><b>8. CHILDREN’S AND MINOR’S PRIVACY </b></h4>
<p>We strongly encourage parents and guardians to supervise the online activities of their minor children and consider using parental control tools available from online services and software manufacturers to help provide a child-friendly online environment. These tools can also prevent minors from disclosing their name, address, and other personally identifiable information online without parental permission. Although the Services are not intended for use by minors, We respect the privacy of minors who may inadvertently use the internet or the mobile application.</p>

<h4><b>9.  CONSENT TO THIS POLICY  </b></h4>
<p>You acknowledge that this Privacy Policy is a part of the Terms and Conditions of the Website and the other Services, and you acknowledge that you have unconditionally agreed as User of the Platform and the Services signifies your assent to this Privacy Policy. Your visit to the Website, use of the App and use of the Services is subject to this Privacy Policy and the Terms and Conditions.</p>

<h4><b>10. COOKIES  </b></h4>
<p>When You avail our Services on the Platform, a persistent cookie is placed on Your computer.
<br>
This enables us to track any purchases You make with our participating retailers and award cashback / rewards / points to You. If You do not have such persistent cookies enabled on Your computer You will not be able to earn cashback / points on Your online shopping via Our Platform.
<br>
Disabling/enabling cookies: You have the ability to accept or decline cookies by modifying the settings in Your browser. However, You may not be able to use all the interactive features of Our Platform if cookies are disabled.
<br>
Please note: if You disable the cookies in Your browser which are used to track Your purchases via Our Platform, You will not be able to earn cashback / point when You shop from our website.
<br>
There are a number of ways to manage cookies. If You use different computers in different locations You will need to ensure that each browser is adjusted to suit Your cookie preferences.</p>

<h4><b>11. AMENDMENTS OR CHANGE TO PRIVACY POLICY </b></h4>
<p>Zoogol may update this Privacy Policy at any time, with or without advance notice. In the event there are significant changes in the way Zoogol treats User Information, or in the Privacy Policy itself, Zoogol will display a notice on the Website or send Users an email, as provided for above, so that the User may review the changed terms prior to continuing to use the Services. As always, if the User objects to any of the changes to our terms, and the User no longer wish to use the Services, the User may communicate the same to contact@Zoogol.com to deactivate Your account. Unless stated otherwise, the current Privacy Policy applies to all information that Zoogol has about You and Your account.
<br>
If a User uses the Services after a notice of changes has been sent to such User or published on the Platform, such User hereby provides his/her/its consent to the changed terms.</p>



     </br></br></br></br>

</div>